CREATE DATABASE chat;

USE chat;

CREATE TABLE messages (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED,
  text VARCHAR(140),
  created_at DATETIME,
  room_id INT UNSIGNED,

  PRIMARY KEY (id)
);

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150),

  PRIMARY KEY (id)  
);

CREATE TABLE rooms (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150),

  PRIMARY KEY (id)
);
